### ISSUE TITLE
Chapter 1

### ISSUE THREAD

**Issue by MaxisJaisi** [worstsauce/study#7]
Chapter 1: **Vector Spaces**

**1.A**

- [x] Exercise 1
- [x] Exercise 2
- [x] Exercise 3
- [x] Exercise 4
- [x] Exercise 5
- [x] Exercise 6
- [x] Exercise 7
- [x] Exercise 8
- [x] Exercise 9
- [x] Exercise 10
- [x] Exercise 11
- [x] Exercise 12
- [x] Exercise 13
- [x] Exercise 14
- [x] Exercise 15
- [x] Exercise 16

**Notes on 1.A**

**1.B**

- [x] Exercise 1
- [x] Exercise 2
- [x] Exercise 3
- [x] Exercise 4
- [x] Exercise 5
- [x] Exercise 6

**1.C**

- [x] Exercise 1
- [x] Exercise 2
- [x] Exercise 3
- [x] Exercise 4
- [x] Exercise 5
- [x] Exercise 6
- [x] Exercise 7
- [x] Exercise 8
- [ ] Exercise 9
- [x] Exercise 10
- [x] Exercise 11
- [x] Exercise 12
- [ ] Exercise 13
- [x] Exercise 14
- [x] Exercise 15
- [x] Exercise 16
- [x] Exercise 17
- [x] Exercise 18
- [x] Exercise 19
- [x] Exercise 20
- [x] Exercise 21
- [x] Exercise 22
- [x] Exercise 23
- [x] Exercise 24

**Comment by bestsauce** [comment]
Just a note here: You also don't need to do all the exercises. If you want you can remove some, or leave them all.

**Comment by MaxisJaisi** [comment]
@bestsauce I know. I'm leaving them here as I haven't decided on which ones I'll do.

**Comment by bestsauce** [comment]
Should we wait a bit for others or do we start this week? (I also know that there's another person who wants to join, but he'll do so in 2 weeks)

**Comment by MaxisJaisi** [comment]
@bestsauce Starting this week is fine by me. What do you think? Or perhaps we should wait for another week for the other 2 to respond? I think one more week would be the ultimatum, or else the study group would never kick off...

**Comment by bestsauce** [comment]
@MaxisJaisi That sounds like the right plan.

**Comment by MaxisJaisi** [comment]
@bestsauce  By the way, are you an undergrad? What math courses have you taken, and what courses are you taking? I'm currently working my way through Stein's Fourier Analysis and Zorich's Mathematical Analysis, and am worried that 1 week per chapter might be too optimistic (the first few chapters are fine, but the latter chapters might take quite a while). But I'll try to get things done in a week. I'm just trying to get a first glimpse of abstract linear algebra, so I'm not worried about getting all the gory details right.

**Comment by bestsauce** [comment]
@MaxisJaisi No, I'm not currently. I only took Calc. Also one chapter per week was only my suggestion, I have no problem with your proposal that we should extend it (after finishing the first few chapters) to something longer. :)

**Comment by bestsauce** [comment]
@MaxisJaisi Just to confirm, you're ready to start working by Monday?

**Comment by MaxisJaisi** [comment]
@bestsauce Yeah.

**Comment by bestsauce** [comment]
@MaxisJaisi Thanks! Do you know how to create date milestones and set them in Github? (Also I deleted some comments here to cleanup the discussion)

**Comment by MaxisJaisi** [comment]
@bestsauce No, I don't, unfortunately. :( I'm completely new to this Github thing.

**Comment by bestsauce** [comment]
@MaxisJaisi Don't worry it's pretty easy: https://github.com/worstsauce/study/milestones

I've created one for 30 April which we'll set for both of us.

**Comment by MaxisJaisi** [comment]
@bestsauce All right, let's learn ourselves some Linear Algebra! (=

**Comment by bestsauce** [comment]
> I found Exercise 11 odd. What's the deeper significance of the exercise?

AFAIK none other than showing that no solution exists for that system.

(BTW it would be better if you left questions in a new comment rather than edit the OP)

**Comment by MaxisJaisi** [comment]
@bestsauce Noted. What do you think about writing down solutions to selected problems in the OP? I want to record proofs of stuff that aren't just exercises without a deeper significance (like Ex 11), especially simple results about general vector spaces and stuff that are used over and over again. Do them in the OP, or comment?

**Comment by MaxisJaisi** [comment]
@bestsauce  Also, would it be okay to post solutions here? Is there a "spoiler" feature that's available so I can hide them in case you don't wanna see them here?

**Comment by bestsauce** [comment]
> Noted. What do you think about writing down solutions to selected problems in the OP? I want to record proofs of stuff that aren't just exercises without a deeper significance (like Ex 11), especially simple results about general vector spaces and stuff that are used over and over again. Do them in the OP, or comment?

OP. But if you have a doubt about some solution you made you should add it in a comment.

> Also, would it be okay to post solutions here? Is there a "spoiler" feature that's available so I can hide them in case you don't wanna see them here?

There's no spoiler feature that's why I said to keep questions in the comments so that they're distinct from solutions in the OP :)

**Comment by bestsauce** [comment]
One comment on your solution for Ex2: The step "If $a=0$, we're done" is unnecessary, you can immediately assume that $a\neq0$ and proceed with your proof and it would be sufficient, since $$P\implies(Q\lor R)\equiv (P\land \neg Q)\implies R.$$

**Comment by bestsauce** [comment]
One comment on your solution for Ex2: The step "If $a=0$, we're done" is unnecessary, you can immediately assume that $a\neq0$ and proceed with your proof and it would be sufficient, since $$\Big\\{P\implies(Q\lor R)\Big\\} \iff \Big\\{(P\land \neg Q)\implies R\Big\\}.$$

**Comment by bestsauce** [comment]
One comment on your solution for Ex2: The step "If $a=0$, we're done" is unnecessary, you can immediately assume that $a\neq0$ and proceed with your proof and it would be sufficient, since $$\Big\{P\implies(Q\lor R)\Big\} \iff \Big\{(P\land \neg Q)\implies R\Big\}.$$

**Comment by MaxisJaisi** [comment]
Interesting. I've never considered this logical subtlety before. In all the proofs that I've done which have these "trivial cases", I've always written " If blah, then we're done. Else, blah...". And a lot of books and papers do it this way. Where did you read about this logical equivalence? Or did you stumble upon it on your own?

**Comment by MaxisJaisi** [comment]
I think I've drawn truth tables to establish this equivalence when I first learned basic propositional logic, but it never occurred to me that it can be used as a "stylistic improvement" in writing proofs...

**Comment by bestsauce** [comment]
@MaxisJaisi I learned it from a book offering an introduction to propositional logic and proofs (can't remember which).

**Comment by bestsauce** [comment]
@MaxisJaisi Just wanted to see if you got some different examples for Ex7-8:

* For Ex7: We can take as an example the lattice $\mathbf{Z}^2$.
* For Ex8: We can take the set $\big\{(x,y)\big| xy\geqslant0\big\}$.

**Comment by MaxisJaisi** [comment]
I guess I'm done with Chapter 1. I'll leave the problem on periodic functions blank, because 1) I tried and couldn't find a counterexample, 2) It was quite intuitively clear that the sum of periodic functions that I could think of were also periodic functions, until I stumbled upon the counterexamples involving irrational periods, and 3) the general proof involving contradiction isn't that easy to find.

As for Exercise 13, I'll leave it aside for now, and come back to it in the future. I feel a little bit uncomfortable about my tendency to assume that my vector spaces have $\mathbf{F}$ as their ambient fields. I'm not sure if any of the results I proved would fail for fields other than $\mathbf{C}$ or $\mathbf{R}$.

**Comment by bestsauce** [comment]
@MaxisJaisi Here's what I did concerning the question on periodic functions:
Assume $f$ has period $p$ and $g$ has period $d$ (with $p\neq d$), then $$(f+g)(x+p)=f(x+p)+g(x+p)=f(x)+g(x+p)\neq f(x)+g(x).$$ As such it can be easy to find a counterexample by picking functions with different periods such as $f:x\mapsto \sin x$ and $g:x\mapsto \sin\pi x$.

**Comment by MaxisJaisi** [comment]
@bestsauce I don't understand your first line. What you've shown is that $f+g$ does not have period $p$. But how do you know it's not periodic? How does it help with the counterexample? Any two periodic functions with rational periods sum to a periodic function, but I don't see any mention of irrationality in your analysis.

**Comment by MaxisJaisi** [comment]
@bestsauce For example, $f$ and $g$ given by $f(x)=\sin(x)$ and $g(x)=\sin(2x)$ clearly have different periods, but they sum to a function with period $2 \pi$.

**Comment by bestsauce** [comment]
@MaxisJaisi With your two examples they do not satisfy the criteria that I wrote which was $f(x)+g(x+p)\neq f(x)+g(x)$ where $p$ is the period of $f$.

**Comment by bestsauce** [comment]
In other words, you should pick a $g$ with $g(x+p)\neq g(x)$ (where $p$ is the period of the first function $f$)

**Comment by MaxisJaisi** [comment]
Okay, suppose I pick $f$ and $g$ where $f(x)=\sin({\frac{34}{7}} x)$ and $g(x) = \sin({\frac{33}{7}} x)$. Then $g(x + {\frac{7}{17}} \pi) \neq g(x)$, where $\frac{7}{17} \pi$ is the period of $f$. But $f+g$ is still periodic.

**Comment by bestsauce** [comment]
@MaxisJaisi That's right, seems like there must be other conditions... Reserving this for my to-do list! In the meantime we have the $f:x\mapsto \sin x$ and $g:x\mapsto \sin\pi x$ counterexample.

**Comment by MaxisJaisi** [comment]
@bestsauce I felt that your condition wouldn't work because you didn't mention anything about the rationality of the periods. Rational periods are crucial, because if you have two functions with differing periods, but are rational, then the sum will always be periodic with respect to their common periods (take the **LCM** of both periods). You can't simply take the LCM of irrational numbers, so using this trick, one can construct a sum of two periodic functions which isn't periodic (e.g. your example). There seems to be a deep theory behind periodicity of functions, which is highly interesting (that's in my to-do list as well), but I'll leave it aside for now. (=

**Comment by bestsauce** [comment]
@MaxisJaisi Yes, after thinking about it for a bit it seems that evaluating $f+g$ at $x+p$ is not the right choice. $f+g$ may be periodic with its own different period from the period of $f$ or the period of $g$.

**Comment by bestsauce** [comment]
@MaxisJaisi Well that motivated me for creating a separate thread to think about such questions: https://github.com/worstsauce/study/issues/8 (feel free to edit the title!)

**Comment by bestsauce** [comment]
Since you're done with chapter 1 I'm closing this to leave room for a chapter 2 thread (you can still participate here concerning the exercise that's left)

**Comment by bestsauce** [comment]
@MaxisJaisi

> Remark: I learned the fact that every function f can be written as an even and an odd function uniquely while working through the first few chapters of Spivak's Calculus some time ago, so this isn't completely new. I doubt I would've hit upon the result if it weren't for Spivak's exercise...

Same here :smile:

**Comment by bestsauce** [comment]
Moved your exercises here: https://github.com/worstsauce/study/blob/master/resources/Chapter%201/Exercises-Maxis.md

**Comment by MaxisJaisi** [comment]
@bestsauce So you worked through Spivak too? Cool. Did you use it for your calculus course, or self-study?

**Comment by bestsauce** [comment]
@MaxisJaisi Unfortunately due to time constraints and some other problems I didn't finish it yet, but I'll be back to it now that I have more spare time. And yes that was self-study.

--

2. May 2017 11:26 by notifications@github.com:
